version: "3.8"

services:
  gateway:
    image: your-gateway-image:latest
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GOLANG_SERVICE_URI=http://account:8082
      - AUTHENTICATION_SERVICE_URI=http://authentication:8081
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    networks:
      - {{ msa_network }}
    depends_on:
      - authentication
      - account

networks:
  {{ msa_network }}:
    external: true

