version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: {{ mysql_root_password }}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - {{ msa_network }}

volumes:
  mysql-data:

networks:
  {{ msa_network }}:
    external: true

